---
ports:
- name: Seattle
  key: 1
  coordinates:
    lat: 12
    lon: 34
- name: Vashon
  key: 2
  coordinates:
    lat: 12
    lon: 34
- name: West Seattle
  key: 3
  coordinates:
    lat: 12
    lon: 34
sailings:
  weekday: []
  saturday: []
  sunday: []
